[[Libgcrypt]]
arch = "aarch64"
git-tree-sha1 = "aa9cd3bc048840ad472f864c1140ab046a6d1a8e"
os = "macos"

    [[Libgcrypt.download]]
    sha256 = "2cda0e29fb68b3a9e6a6d52e0c76250eeae62c23f934b70cf87ab1fa924f5e27"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.aarch64-apple-darwin.tar.gz"
[[Libgcrypt]]
arch = "aarch64"
git-tree-sha1 = "9a78271070566275220e78c9f63e6ef5529abf13"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "59a656421f954c917d4e2b893fed9fe25789803dab9e2d3bc660dea9a1866dae"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.aarch64-linux-gnu.tar.gz"
[[Libgcrypt]]
arch = "aarch64"
git-tree-sha1 = "97d0f9cbac366fd14af052972b051198b3d70691"
libc = "musl"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "fc9f8131005b35cd5d566b48fef5ba11c2275a0e3ad52fd056e06471bfa04e30"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.aarch64-linux-musl.tar.gz"
[[Libgcrypt]]
arch = "aarch64"
git-tree-sha1 = "a64a109dbc426287c00b37903a69bcc05d623e52"
os = "freebsd"

    [[Libgcrypt.download]]
    sha256 = "c1f9b379b38bdc89a702bc66f35bb465af7a596ab67055dcbf4ede69ad36a648"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.aarch64-unknown-freebsd.tar.gz"
[[Libgcrypt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a6423ba8f058d7d7399f92f1381594996aaf73d5"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "d5e57065afbd99a3bdeb75cc9704e16602b58975f6927fde3b6a2dfaa598b93a"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.armv6l-linux-gnueabihf.tar.gz"
[[Libgcrypt]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a5c078c002ab3765285eaa54dc5008614772aff8"
libc = "musl"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "125594b90366fcda9fd1293b83b9690c7391a5b26b0470df2105d3bcda2a50ad"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.armv6l-linux-musleabihf.tar.gz"
[[Libgcrypt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "20a2893ba0056e2cdefc10c4b06bc414293cc58d"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "96c614fd462d4fc5b8cfe5b971da4d889a86fe095ba22b391c1bcc36ab8d4cbf"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.armv7l-linux-gnueabihf.tar.gz"
[[Libgcrypt]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ac84c4bbe50e0acf1f658afccc5fe0ed1bfb3dbf"
libc = "musl"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "a2982b4393852b5fb7ca162d0f99d122a5160f78778aeb5adb30ac67e2373ce3"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.armv7l-linux-musleabihf.tar.gz"
[[Libgcrypt]]
arch = "i686"
git-tree-sha1 = "2b9098c9f6dc447167d16713c2c086853a281576"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "3caabaf2d6b741ee002236dfa877366774651f2d65ed3787a86b58f93f7a4de2"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.i686-linux-gnu.tar.gz"
[[Libgcrypt]]
arch = "i686"
git-tree-sha1 = "407662981f7bff3f088f257b374306ccfcddc6ad"
libc = "musl"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "7d25c9648e8cb9c34a6380cb91677fca82ebab1530015194c8c9f2d6a160ece6"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.i686-linux-musl.tar.gz"
[[Libgcrypt]]
arch = "i686"
git-tree-sha1 = "3ad5d667cde629059261ba1dd600ce22c1acf3bd"
os = "windows"

    [[Libgcrypt.download]]
    sha256 = "f73e2e8ca7a96cb8ad28dc7052beb36be95000921a2a90c9b5d036806a492248"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.i686-w64-mingw32.tar.gz"
[[Libgcrypt]]
arch = "powerpc64le"
git-tree-sha1 = "4973925c7f080478ec633f67b8e98cfc49d77be3"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "ad542cbf17a1ada7e5a1d6c8239b9c3aa1dba16c1e8ede7c4ec5506825b03715"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.powerpc64le-linux-gnu.tar.gz"
[[Libgcrypt]]
arch = "riscv64"
git-tree-sha1 = "d0e15917aa2d5f3b17b290476748905240833aae"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "071ac6a470f22983beeb13ac811f56885ef83991c9f781d52def4dcdee79f854"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.riscv64-linux-gnu.tar.gz"
[[Libgcrypt]]
arch = "x86_64"
git-tree-sha1 = "15b34adf2a85b0d68d1b44f4754c370e211ead09"
os = "macos"

    [[Libgcrypt.download]]
    sha256 = "db0f0202288046eeb00ad7bb46d3b49ff88fc30398aa5aa288f1525bce8a2d6f"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.x86_64-apple-darwin.tar.gz"
[[Libgcrypt]]
arch = "x86_64"
git-tree-sha1 = "16c3dad9e41ce010febb5beaa2d92dde6a3792d4"
libc = "glibc"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "1a5dea45fecaa90765d9a0ef6aa3d25b922320bf3e809949c7724dfe230d1810"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.x86_64-linux-gnu.tar.gz"
[[Libgcrypt]]
arch = "x86_64"
git-tree-sha1 = "5aac0582884b9e8d8b515d7cc6ebaf2140f23a68"
libc = "musl"
os = "linux"

    [[Libgcrypt.download]]
    sha256 = "dec8748eec1db035331d72b77e265a5d12eaffbcd623e712ec5bf86cbdc79cae"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.x86_64-linux-musl.tar.gz"
[[Libgcrypt]]
arch = "x86_64"
git-tree-sha1 = "5907f67833184bf78a3edb4eddb4f42505afb9a9"
os = "freebsd"

    [[Libgcrypt.download]]
    sha256 = "6672025e386f959a3bf4ca19ab879a28cade875ccb7c68a8ce48b1346dbab0b8"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.x86_64-unknown-freebsd.tar.gz"
[[Libgcrypt]]
arch = "x86_64"
git-tree-sha1 = "a17c952ac2d812b5b984d54c0e6695c3f2110774"
os = "windows"

    [[Libgcrypt.download]]
    sha256 = "2e8f054a7719ae42cd9c4ab9cb6ae9dce367395f61c9ce83c299b60a52c58b24"
    url = "https://github.com/JuliaBinaryWrappers/Libgcrypt_jll.jl/releases/download/Libgcrypt-v1.11.2+0/Libgcrypt.v1.11.2.x86_64-w64-mingw32.tar.gz"
